version: '{branch}.{build}'
branches:
  only:
  - /v\d*\.\d*\.\d*/
skip_non_tags: true
image: Visual Studio 2017
build_script:
- cmd: >-
    set CMAKE_EXE="cmake.exe"
    set DESTINATION="wrappers\winrt\UAP\v0.8.0.0\ExtensionSDKs\ZXingWinRT\1.0.0.0"
    set BASE_DIR="%CD%"

    cd %DESTINATION%
    set DESTINATION=%CD%
    
    cd %BASE_DIR%
    set BUILD_LOC=build_uwp_x86
    md %BUILD_LOC%
    cd %BUILD_LOC%
    %CMAKE_EXE% -G "Visual Studio 15 2017" -A Win32 -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 -DEXTENSION_SDK_OUTPUT="%DESTINATION%" ..\wrappers\winrt
    %CMAKE_EXE% --build . --config Release
    
    cd %BASE_DIR%
    set BUILD_LOC=build_uwp_x64
    md %BUILD_LOC%
    cd %BUILD_LOC%
    %CMAKE_EXE% -G "Visual Studio 15 2017" -A x64 -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 -DEXTENSION_SDK_OUTPUT="%DESTINATION%" ..\wrappers\winrt
    %CMAKE_EXE% --build . --config Release

    cd %BASE_DIR%
    set BUILD_LOC=build_uwp_arm
    md %BUILD_LOC%
    cd %BUILD_LOC%
    %CMAKE_EXE% -G "Visual Studio 15 2017" -A ARM -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 -DEXTENSION_SDK_OUTPUT="%DESTINATION%" ..\wrappers\winrt
    %CMAKE_EXE% --build . --config Release

    cd %BASE_DIR%
    set BUILD_LOC=build_uwp_arm64
    md %BUILD_LOC%
    cd %BUILD_LOC%
    %CMAKE_EXE% -G "Visual Studio 15 2017" -A ARM64 -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 -DEXTENSION_SDK_OUTPUT="%DESTINATION%" ..\wrappers\winrt
    %CMAKE_EXE% --build . --config Release

    cd %BASE_DIR%
    for /f "tokens=1,2,3 delims=. " %%a in ("%APPVEYOR_BUILD_VERSION%") do set major=%%a&set minor=%%b&set patch=%%c&set
    nuget pack -Version %major%.%minor%.%patch% wrappers\winrt\nuget\ZXingWinRT.nuspec
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: OMvgm0WQ+yV7E+yxtmrOn6c/uO/V1fsbBERdz9aQUicqHGImzWqWoSBAankUtxdEwDZx0XrJ5hlUsIuL5tdQD+C8ZKrI1L3FukbXdbqVdKM=
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true
